choco install -y 7zip.install
choco install -y agentransack
choco install -y bulkrenameutility.install
choco install -y ccleaner
choco install -y chocolateygui
choco install -y dotnetcore-runtime.install
choco install -y dotnet-runtime
choco install -y dotnetfx
choco install -y dropbox
choco install -y firefox
choco install -y googlechrome
choco install -y keepass.install
choco install -y notepadplusplus
choco install -y patchcleaner
choco install -y sysinternals
choco install -y treesizefree
