choco install -y git.install
choco install -y ilspy
choco install -y lua53
choco install -y nodejs.install
choco install -y poshgit
choco install -y python3
choco install -y visualstudio2022community
choco install -y vscode
choco install -y yarn
